#如果指定pro/dev这里就不管用了
server:
  port: 9090
#prod环境spring.profiles.active=prod  dev 优先application-prod.properties配置
spring:
  profiles:
    active: dev
#多数据源
  main:
    allow-bean-definition-overriding: true
  # redisson分布式锁
#  redis:
#    database: 0 # redis数据库索引(默认0)
#    host: 127.0.0.1 # redis服务器地址
#    port: 6379 # redis服务器连接端口
#    password: # redis服务器连接密码(默认空)
#    jedis:
#      pool:
#        max-active: 200 # 连接池最大连接数(使用负值表示没有限制)
#        max-wait: -1 # 连接池最大阻塞等待时间(使用负值表示没有限制)
#        max-idle: 10 # 连接池中的最大空闲连接
#        min-idle: 0 # 连接池中的最小空闲连接
#    timeout: 1000 # 连接超时时间(毫秒)
#  redis:
#    host: 127.0.0.1 
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 500
#        min-idle: 0
#      lettuce:
#       shutdown-timeout: 0

# spring.mvc:
#    view:
#      prefix: /view/  
#      suffix: .jsp
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/sxxl_analysis?characterEncoding=UTF-8
 #   username: root
 #   password: root
 #   driver-class-name: com.mysql.jdbc.Driver
#spring:
  jmx:
    enabled: false  
  
#1、com.controller.readofyml.author 测试调用成功  
author:
  name: 小鹏
  csdnUrl: http://www.baidu.com
#/2、yml 需要在 “:” 后加一个空格      com.controller.readofyml.HelloController在调用测试成功
name: xiaoxiao
csdnUrl: http://www.basd.dsdds
content: "name:${name},csdnUrl:${csdnUrl}"
upload:
  dir: 测试路径
#com.demomodel.appListener.contextRefreshedEvent.DahuaAuthorization2测试成功
ip: 192.132.2.2
port: 2332
userName: sa
password: sc